yj-yuee/수학/250804/설탕배달.py
- **문제 제목**: 설탕 배달
- **문제 링크**: https://www.acmicpc.net/problem/2839
- **플랫폼**: 백준
- **난이도**: 실버4
전체 봉지 개수를 최소화하려면 , 가장 큰 5kg 봉지를 최대한 많이 사용해서 풀어야함
1.  5로 최대로 나누고 남은 수를 3 으로 나누고 나눠지면 성공, 안나눠지면 -1
2.  탐색 실패시 5kg 를 하나 씩 빼서 3으로 다시 나누고 나눠지면 성공 , 안나눠지면 -1 을 반복
3.  5kg를 하나도 사용하지 않았는데 3kg로도 나눠지지 않는 경우 탐색 불가능
1. 조건을 한번 탐색하고 맞지않을시 계속 탐색해야하는게 어려웠음.
5. N // 5 조건에서 5kg 봉지를 전혀 사용하지 않는 경우(즉, i=0인 상황) 을 고려하지않아 불필요한
if N < 5 and N % 3 != 0:
result = -1
elif N < 5 and N % 3 == 0:
result = 1
비교 코드를 만들었음 . 
6. range 의 stop 부분을 -1로 변경하고 주요 코드에 전체 탐색을 구현해 마무리했음
5kg 봉지 개수를 최댓값에서부터 1씩 줄여나가며, 남은 무게가 3으로 나누어떨어지는 최초의 조합 찾기
경계값 및  완전 탐색 범위를 제대로 설정하는게 중요하다는 것을 배움 
처음 문제 고민 시에 최대한 많은 케이스를 고려해 범위를 설정해야함
=> [250804]수학 문제 풀이 / yj-yuee

jh/문자열/BOJ_10809_문자열_찾기.py
- **문제 제목**: 알파벳 찾기
- **문제 링크**: https://www.acmicpc.net/problem/10809
- **플랫폼**: BOJ
- **난이도**: 브론즈2
알파벳 소문자로만 이루어진 단어 S를 받아 각각의 알파벳에 대해서 알파벳이 처음 등장하는 위치를 출력한다.
만약 단어 S에 알파벳이 포함되어 있지 않다면 -1을 출력한다.
a 부터 z 까지 리스트를 생성하고 단어 S의 알파벳을 순서대로 탐색하며 알파벳 리스트에 단어의 알파벳 인덱스를 삽입한다.
이중 for문에서 알파벳 리스트를 먼저 탐색해야 할지, 단어 S를 먼저 탐색해야 할지 헷갈렸다.
- **시간**: O(n^2)  **공간**: O(n)
알파벳 리스트를 먼저 순회하며 단어 S에 있는 알파벳과 일치 여부를 판단하여 맞으면 인덱스를 삽입하고 break, 없다면 -1을 삽입한다.
이중 for문 구조에서 어떤 리스트를 먼저 순회해야 하는지
리스트 순회, 리스트 인덱스, 리스트 값 수정
이중 for문을 사용하지 않고 시간 복잡도를 줄이고 싶다.
=> [BOJ-10809] 알파벳 찾기/jxn-hxxn

sm/수학/BOJ_5086_sm.py
- **문제 제목**: 배수와 약수 
- **문제 링크**: https://www.acmicpc.net/problem/5086
- **플랫폼**: BOJ
- **난이도**: Bronze 3
두 수를 비교하여 서로의 관계가 배수인지 약수인지 판단하는 문제
입력값 0 0 을 받으면 종료
if문 과 산술연산자를 사용하여 나머지가 0일때를 찾아보았다
입력값 0 0 을 받으면 break
다음에는 더 어려운 문제를 해야겠다.
break를 사용하기 위해 while문이 필요
산술연산자의 이해
x
if, elif와 else에 대해 헷갈렸는데 확실하게 이해하게 되었다.
최대공약수와 최소공배수, 소수를 구하는 방법으로 확장해보고 싶다.
=> [BOJ-5086 배수와약수/Sng-mnn ]

eoyeou/수학/20250805/BOJ_1934.py
- **문제 제목**: 최소공배수
- **문제 링크**: https://www.acmicpc.net/problem/1934 
- **플랫폼**: 백준
- **난이도**: 브론즈1
- 두 수의 최소공배수 구하기
- 두 수의 최대공약수를 먼저 구한 뒤, 최소공배수를 계산
처음에 반복문에서 for tc in T: 라고 작성해서 TypeError 발생 -> range(T)로 수정
- **시간**: O(log)  **공간**: O(1)
- 유클리드 호제법 활용
- 정수로 순회할 수 없다. 항상 범위 신경쓰기
- GCD/LCM 개념 활용한 다양한 문제 풀어보기
=> [250805] 수학 문제풀이 / eoyeou

week_algorithm/week_quest_1/Sng-mnn_소수구하기.py
- **문제 제목**: 소수 구하기
- **문제 링크**: https://www.acmicpc.net/problem/1929
- **플랫폼**: BOJ
- **난이도**: 실버 3
1이상의 자연수 M에서부터 N까지의 소수를 구하기
소수가 아님을 판별하여 제거한 후 나머지 수 출력
x
약수가 있을경우 cnt를 증가시키고
cnt가 0일 경우 출력
x
x
어제 daily quest로 풀었던 것과 유사하여 다행이다...
=> [250806] 수학 문제풀이/Sng-mnn

week_algorithm/week_quest_1/ys_소수.py
- **문제 제목**: 소수
- **문제 링크**: https://www.acmicpc,net/problem/1929
- **플랫폼**: 백준
- **난이도**: 실버3
- M이상 N이하의 소수를 출력
- 소수 판별할 때 루트n까지만 확인
- for문으로 M부터 N까지 소수판별 후 출력
M,N = int(input().split())에서 split()결과에 int()를 바로 적용해서 TypeError 발생
- 루트 n까지만 확인
- 소수 판별시 루트 n까지만
- 에라토스테네스의 체 방식으로도 구현해서 속도 차이 비교
=> [250806]수학문제풀이/eoyeou

sm/수학/BOJ_2563_sm.py
- **문제 제목**: 색종이
- **문제 링크**: https://www.acmicpc.net/problem/2563
- **플랫폼**: BOJ
- **난이도**: 실버5
색종이로 덮힌 도화지의 넓이 구하기
색종이가 덮힌 부분에 1의 값을 주었다.
겹쳐지더라도 숫자를 더하지 않았다.
행의 인덱스를 구할때 수학에서의 x,y좌표와 파이썬 배열에서의 row, col인덱싱 사이에서 헷갈렸다.
수업시간에 배운 2차원 배열 안에 2차원배열에 진입하는것
x,y좌표와 row,col좌표의 차이점과 유사점
더 복잡한 2차원 배열 문제를 풀어보고싶다
=> [250806]기타문제풀이 / Sng-mnn

jh/문자열/BOJ_1157_단어_공부.py
- **문제 제목**: 단어 공부
- **문제 링크**: https://www.acmicpc.net/problem/1157
- **플랫폼**: BOJ
- **난이도**: 브론즈1
알파벳 대소문자로 이루어진 단어를 입력받아 가장 많이 사용된 알파벳을 대문자로 출력한다.
만약 가장 많이 사용된 알파벳이 여러개인 경우에는 ?를 출력한다.
딕셔너리를 사용해 입력받은 알파벳과 그 개수를 저장했다.
알파벳의 개수인 value 값을 비교하여 가장 많이 사용된 알파벳을 찾았고,
가장 많이 사용된 알파벳이 여러개인 경우도 조건을 걸어 찾았다.
딕셔너리를 오랜만에 사용해 데이터를 추가하고 활용하는데 조금 어려움을 겪었다.
- **시간**: O(n)  **공간**: O()
딕셔너리 자료구조를 사용한 것
딕셔너리 구조를 오랜만에 사용해 조금 헷갈렸다.
딕셔너리 구조에 데이터를 입력하고 활용하는 방법
내가 작성한 코드보다 더욱 짧고 단순하게 작성하도록 해보겠다.
=> [250808] 기타 문제 풀이 / jxn-hxxn

week_algorithm/week_quest_1/Sng-mnn_골드바흐의추측.py
- **문제 제목**: 골드바흐의 추측
- **문제 링크**: https://www.acmicpc.net/problem/9020
- **플랫폼**: 백준
- **난이도**: 실버1
2보다 큰 짝수가 주어졌을때 골드바흐 파티션을 출력하라
에라토스테네스의 체로 10,000 이하 소수를 미리 구하고, n의 절반에서 시작해 양쪽으로 확장하며 두 소수를 찾음
범위 초과로 인한 인덱스 오류 가능성과 입력 처리 속도 최적화 부분
중앙값부터 탐색하면 처음 발견한 소수 쌍이 곧 차이가 가장 작은 골드바흐 파티션임
시간이 많이 들긴했지만 많은 것을 배운거같다.
중앙값부터 탐색해 조건을 빠르게 만족시키는 알고리즘
=> [250809] 수학문제풀이 / Sng-mnn

yj-yuee/정렬/250809/수정렬하기3.py
- **문제 제목**: 수 정렬하기 3
- **문제 링크**: https://www.acmicpc.net/problem/10989
- **플랫폼**: 백준
- **난이도**: 브론즈 1
주어진수 정렬하기
카운트정렬, 버블정렬, 선택정렬로 각각 정렬해보기
카운트정렬 누적합을 이해하는데 오래걸렸다.
배운 정렬로 풀어보기
카운트정렬이 누적합을 사용해서 할때 생각보다 바로 풀지못해서 연습할필요가있다고 생각했다.
정렬문제를 더 풀어봐야겠다.
=> [250809] 기타 문제 풀이 / yj-yuee

yj-yuee/구현/250810/Flatten.py
- **문제 제목**: Flatten
- **문제 링크**: https://swexpertacademy.com/main/talk/solvingClub/problemView.do?solveclubId=AZgSFmP6tCjHBIN_&contestProbId=AV139KOaABgCFAYh&probBoxId=AZh3mD3ajrzHBINp&type=PROBLEM&problemBoxTitle=250805+List&problemBoxCnt=5
- **난이도**: D3
상자를 옮겨 평탄화하기
수업시간에는 함수없이 구현했는데 함수를 이용해 구현해봤다.
min,max를 구한뒤 원래 리스트에서 값을 +1-1을 반복했다.
둘의 차가 1,0이면 반복을 중지 후 
두수의 차를 출력
최종 변경된 리스트에서 차를 구하지않고 a, b 로 구했는데 10개의 테스트 케이스중 9개만 통과했다.
마지막 반복실행전 가장 높은상자가 여러개거나 낮은 상자가 여러개였을 경우에 발생하는 변수를 생각하면 
최종 리스트에서 다시 max, min을 구하는게 가장 정확한 답이였다.
최대, 최소
테스트 케이스를 통과못할때 비교해 보는 법을 배웠다.
깊게 생각하기
=> [250810] 기타 문제 풀이 / yj-yuee

sm/배열/우주괴물.py
- **문제 제목**: 우주괴물
- **문제 링크**: https://swexpertacademy.com/main/talk/solvingClub/problemView.do?solveclubId=AZgSFmP6tCjHBIN_&contestProbId=AZU7flp6n8XHBIRK&probBoxId=AZiXyja6JuPHBINp&type=USER&problemBoxTitle=%EC%97%AD%EB%9F%89%ED%8F%89%EA%B0%80%EB%8C%80%EB%B9%84+%EB%B3%B4%EC%B6%A9+%EB%AC%B8%EC%A0%9C&problemBoxCnt=8
- **난이도**: D1
괴물의 레이저가 닿지 않는 안전한 구역 찾기
괴물의 좌표 찾기 - 괴물의 좌표로부터 delta를 사용해 laser구하기 - 구하는 도중 벽을 만나면 정지
벽을 만났을때 멈추게 하는 코드를 생각하는데 시간이 오래 걸림
벽을만나면 break, 아니면 리스트에 append
=> [250811] 기타 문제풀이 / Sng-mnn

hemu/배열/20250812/SWEA_풍선펑.py
- **문제 제목**: 풍선팡 보너스 게임2
- **문제 링크**: https://swexpertacademy.com/main/code/userProblem/userProblemDetail.do?contestProbId=AY3FFOTaN7EDFAXh
- **난이도**: D2
주어진 기준점에서 상하좌우 방향으로 풍선을 터뜨린다.
델타를 사용하여 상하좌우를 터뜨렸을때 최댓값을 찾았다.
델타를 사용
다른 역량평가 문제를 풀어봐야겠다.
=> [250812] 기타 문제 풀이/hemu

eoyeou/문자열/20250812/SWEA_3143_ys.py
- **문제 제목**: 가장 빠른 문자열 타이핑
- **문제 링크**: https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV_65wkqsb4DFAWS
- **난이도**: D4
- A를 타이핑할 때 단축키 누르면 B가 한번에 입력
- A를 타이핑하는 데 필요한 최소 키 입력 횟수 구해야 함
- KMP 알고리즘을 사용해 A 안에서 B가 등장하는 모든 시작 위치를 구함
- 위치들을 돌면서 겹치지 않도록 선택 -> 단축키 사용 횟수 결정
- B 단축키를 누르면 원래는 len(B)번 눌러야 되는데 1번으로 줄어든다
- KMP의 점프 로직 이해가 어려웠다
- 패턴 검색은 KMP로 빠르게 찾기
- 찾은 위치 중에서 겹치지 않게 최대한 많은 것을 선택
- LPS 배열과 KMP 알고리즘을 이해했다고 생각했는데 코드로 로직을 구현할 때 실수가 많았다.
- 루프 내부에서 length를 줄인 뒤에 다시 pattern[i]와 비교하는 구조를 처음에는 이해하기 어려웠다.
- length를 먼저 증가시킨 뒤에 그 값을 lps[i]에 기록해야 되는데 순서를 바꿔서 오류가 발생했다.
- 문자열 매칭 문제에서 KMP를 활용하면 모든 매치 위치를 구할 수 있다.
- 오늘 문제 여러 개 올리려고 했는데 대실패
- 연관 문제들을 풀어서 익숙해지도록..
=> [250812] 기타문제풀이 / eoyeou

yj-yuee/dfs/250813/바이러스.py, yj-yuee/구현/250812/스위치조작.py
- **문제 제목**: 바이러스
- **문제 링크**: [BOJ-2606] 바이러스 / yj-yuee
- **플랫폼**: 백준
- **난이도**: 실버 3
DFS/BFS
웜바이러스가 네트워크를 통해 전달된다. 1번 컴퓨터가 웜바이러스에 걸렸을때 같은 네트워크에 연결된 컴퓨터도 전염되는데 
이때 전염된 컴퓨터 수 구하기
1번컴퓨터랑 이어진 컴퓨터들을 탐색했다.
1번 컴퓨터로 인해 감염된 컴퓨터의 개수를 구해야하는데 1번 까지 카운트를 했다.
DFS
dfs복숩을 했다.
익숙해질때 까지 풀어보는게 좋을것 같다.
=> [250813] 기타 문제 풀이 / yj-yuee

week_algorithm/week_quest_3/yj-yuee_피보나치수의확장.py
- **문제 제목**: 피보나치 수의 확
- **문제 링크**: https://www.acmicpc.net/problem/1788
- **플랫폼**: 백준
- **난이도**: 실버 3
피보나치 수열이 음수로 주어져도 가능하게 구하기
피보나치 수를 구하는 기본 반복문에서 변형하는게 좋을것 같다고 생각했다.
F(n-2) = F(n)-F(n-1) 이기 때문에 과거항을 찾듯이 
-1, -2 -3 을 넣어보면 기본 피보나치 수열에서 부호만 다르게 나온다.
n = 짝수일때 음수 , 홀수일때 양수가 나오기 때문에 이조건을 활용해서 결과값을 냈다.
문제를 읽고 이해하는데 오래걸렸다.  F(n-2) = F(n)-F(n-1) 이게 어려워서 -4까지 써봤다.
제일 기본 피보나치 반목문을 수정했기 때문에 조건만 잘 만들면 결과가 나왔다.
피보나치수열, 
모르겠으면 써서 풀어보자
피보나치 수열을 구하는 방법중 재귀도 있는데
재귀로도 풀어보면 좋을 것 같다.
=> [250813]수학 문제 풀이 / yj-yuee

jh/수학/SWEA_스위치_조작.py
- **문제 제목**: 스위치 조작
- **문제 링크**: https://swexpertacademy.com/main/code/userProblem/userProblemDetail.do?contestProbId=AZHA7Cn6ZgsDFAQP
- **난이도**: D1
N개의 전등이 설치되어 있고 켜짐 꺼짐 상태가 0과 1로 주어진다. i번째 스위치를 조작하면 i번째부터 N번째까지 전등이 상태가 바뀐다.
A 상태의 전등을 B 상태로 바꾸기 위해서는 최소 몇 번의 조작이 필요한지 알아내는 코드를 작성한다.
처음에는 스위치를 조작해서 바뀐 상태를 업데이트하는 코드를 작성할까 생각해봤다.
스위치를 조작하면 뒤에 어떤 조건에 스위치를 다시 조작해야 하는지를 생각해서 문제를 풀어봤다.
풀이 방법을 생각해내는데 시간이 좀 걸렸다.
A와 B를 비교해서 첫번째 다른 부분이 있으면 스위치 조작.
그 다음에는 초기 상태를 기준으로 같은 부분이 있으면 스위치 조작.
위에 두 조건을 반복.
스위치 조작을 실행하는 아이디어를 생각해내는데 시간이 걸렸다.
불을 잘 끄자
더 쉬운 방법을 생각해 봐야겠다.
=> [250814] 기타 문제 풀이 / jxn-hxxn

hemu/배열/20250814/SWEA_20397.py
- **문제 제목**: 돌뒤집기2
- **문제 링크**: https://swexpertacademy.com/main/code/userProblem/userProblemDetail.do?contestProbId=AY3o7m4axawDFAUZ
- **난이도**: D1
i를 기준으로 마주보고있는걸 비교하여 뒤집는다
i가 인덱스 기준이 아닌 첫번째 , 두번째 와 같이 숫자를 세는 기준임
i의 범위를 설정하고 넘어갈때는 break
범위설정에서 실수를 했어서, 범위설정 연습이 필요한것같다.
i를 기준점으로 잡고 범위 비교
다른 swea 역량평가 대비 문제 풀기
=> [250814]기타 문제 풀이/hemu

yj-yuee/구현/250814/어디에단어가들어갈수있을까.py
- **문제 제목**: 어디에 단어가 들어갈 수 있을까
- **문제 링크**: https://swexpertacademy.com/main/solvingProblem/solvingProblem.do
- **난이도**: D2
단어 퍼즐에 단어 넣기
단어길이 k가 주어지고 딱맞는 자리에 넣어야한다.
예시를 봤을때 K보다 공간이 있어도 들어갈 수 없고 무조건 공간이 K 길이여야 했다.
그래서 단어 퍼즐 리스트를 처음부터 끝까지 한번에 탐색하면서 
이어진 빈칸 의 개수를 세고 0이 나오면 카운트를 멈췄다.
이어진 공간의 수를 한번에 구하는 문제라 한번 들린곳은 안세는 방법을 고민해서 풀었다,
탐색하기
수를 세는거라 습관적으로 델타를 쓰려다가 문제와 맞지않아서 다른 방법을 찾았다. 
문제를 꼼꼼히 읽자
=> [250814] 기타 문제 풀이 / yj-yuee

eoyeou/2차원배열/20250816/SWEA_20397_ys.py, eoyeou/2차원배열/20250816/SWEA_22375_ys.py, eoyeou/2차원배열/20250816/SWEA_23795_ys.py
- **문제 제목**:  돌 뒤집기 게임2
- **문제 링크**: https://swexpertacademy.com/main/code/userProblem/userProblemDetail.do?contestProbId=AY3o7m4axawDFAUZ
- **난이도**: D1
- 돌의 양면 흰색, 검은색
- i번째 돌 사이에 두고 마주보는 j개의 돌 
- 각각 같은 색이면 뒤집고, 다른 색이면 그대로 둔다..
- 범위 벗어나면 중지
- for문으로 반복
- i 기준으로 다르면 건너뛰고, 같으면 바꾸기
- 마주보는 인덱스 설정
- 더 깔끔하게 쓰자
=> [250816] 기타문제풀이 / eoyeou

jh/수학/SWEA_20397_돌_뒤집기_게임2.py
- **문제 제목**: 돌 뒤집기 게임2
- **문제 링크**: https://swexpertacademy.com/main/code/userProblem/userProblemDetail.do?contestProbId=AY3o7m4axawDFAUZ
- **난이도**: D1
동전처럼 앞 뒤면 0과 1로 된 돌의 배열이 주어지고
i번째 돌을 사이에 두고 마주보는 j개의 돌에 대해, 각각 같은 색이면 뒤집고, 다른 색이면 그대로 둔다.
주어진 돌의 배열에 대해 i번째 돌을 기준으로 앞 뒤로 1씩 더하고 빼가면서 비교하여 조건에 맞게 실행했다.
마지막 결과 프린트 할 때 리스트를 값들만 출력하는 방법에 대해 생각했다.
i번째 돌을 기준으로 앞 뒤 값을 비교하며 문제 조건에 맞게 값을 변경시킨다.
마지막 결과값을 프린트 할 때 리스트 값만 출력하는 것에 대해 고민했다.
리스트의 값만 출력하는 방법에 대해 익혔다.
중간의 과정을 함수로 정의해서 코드를 조금 더 깔끔하게 작성해볼 수 있을 것 같다.
=> [250816] 기타 문제 풀이 / jxn-hxxn

hemu/BFS_DFS/250816/SWEA_미로.py
- **문제 제목**: 미로찾기
- **문제 링크**:  https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWTQeET6QlADFAVT
- **난이도**: D2
2에서 출발해 3으로 도착하는 길을 찾는다. 1은 벽 0은 길일때 도착할 수 있으면 1을 반환 없으면 0을 반환
DFS를 사용하여 갈수있으면 true 없으면 false 왔던길은 -1로 바꾸면서 진행
DFS의 구현이 아직도 너무 어렵다.
DFS사용하기
역량 평가 끝나고 dfs문제 더 풀어보며 익히기
=> [250816]기타 문제 풀이/hemu

jh/수학/SWEA_15031_Forth.py
- **문제 제목**: Forth
- **문제 링크**: https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWTQc1MKQiIDFAVT
- **난이도**: D2
Forth라는 컴퓨터 언어는 스택 연산을 기반으로 하고 있어 후위 표기법을 사용한다.
후위 표기법으로 작성된 문자열로 Forth 코드의 연산 결과를 출력하는 프로그램을 만들어라.
만약 형식이 잘못되어 연산이 불가능한 경우 'error'를 출력한다.
stack 구조를 사용했다.
연산 중 에러가 나도 진행되어야 하므로 try/except문을 사용했다.
stack에서 연산을 위해 pop한 수의 연산 순서가 헷갈렸다.
error가 나도 코드가 진행되어야 하므로 try/except 문을 사용했다.
stack 구조를 사용했다.
stack에서 pop한 숫자의 연산 순서가 헷갈려서 제출 시도를 여러번 했다.
후위 표기법 연산에서 연산 순서를 제대로 알 수 있었다.
후위 표기법 연산 순서를 헷갈리지 않겠다.
=> [250820] 기타 문제 풀이 / jxn-hxxn

week_algorithm/week_quest_4/hm_피보나치.py
- **문제 제목**: 피보나치 함수
- **문제 링크**: https://www.acmicpc.net/problem/1003
- **플랫폼**: 백준
- **난이도**: 실버3
-  [ ] 기타:
처음에 재귀를 했다가 또 시간초과가 났다 :(
인간의 욕심은 끝이 없고 똑같은 실수를 반복하지...
for문을 돌면서 a의 인덱스에 값이 없으면 append
재귀,,,
그래도 저번에 피보나치를 한번 해봐서 금방 접근 방법을 찾을 수 있었다.
테스트 케이스 확인해서 재귀 가능한지 먼저 확인하기
=> [20250820] 수학 문제 풀이/hemu

yj-yuee/dfs/250825/길찾기.py
- **문제 제목**: 길찾기
- **문제 링크**: https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV14geLqABQCFAYD
- **플랫폼**: swea
- **난이도**: D4
-  [ ] DFS/BFS
도식화한 지도에서 출발 도착이 가는길이 존재하는지 찾는다
단방향이라 인덱스에 가는 방향만 저장한다.
True false 리스트를 만들어 방문하고 도착지점이면 1을 반환 도착지점을 찾지못하면 0을 반환한다.
dfs 어렵다.
True false, 단방향 리스트 
dfs 문제 10개푼다
=> [250825] 기타 문제 풀이/ yj-yuee

sm/시뮬레이션/로봇청소기.py
- **문제 제목**: 로봇청소기
- **문제 링크**: https://www.acmicpc.net/problem/14503
- **플랫폼**: BOJ
- **난이도**: 골드5
로봇청소기가 청소한 칸의 갯수
조건을 최대한 맞춰서 조건문과 반복문을 작성하였다.
직진으로 이동할 수 있는 경우에도 회전을 먼저하고 직진을 해야한다는 조건을 잘못이해해서 오래걸렸다..
3-2-1-0을 반복하게 하는 것이 어려웠다.
True False를 사용하여 continue와 break를 사용해 시뮬레이션 구현
어렵다..다..
많이 배웠다
시뮬레이션 문제는 연습이 많이 필요한것 같다.
=> [250826] 완전 탐색 &시뮬레이션 문제 풀이 / Sng-mnn

hemu/BFS_DFS/250828/BOJ_1012_배추.py, hemu/BFS_DFS/250828/BOJ_11725_트리의부모찾기.py, hemu/BFS_DFS/250828/BOJ_16236_아기상어.py, hemu/BFS_DFS/250828/BOJ_7576_토마토.py
- **문제 제목**: 아기상어
- **문제 링크**: https://www.acmicpc.net/problem/16236
- **플랫폼**: 백준
- **난이도**: 골드3
자신보다 작은 물고기를 먹고 자기 크기만큼 물고기를 먹으면 성장한다. 자신보다 큰 물고기가 있는 칸은 가지못하고(중요) 자신보다 작거나 같은 칸만 지나갈 수 있다. 더이상 물고기를 먹지못할때 엄마의 도움을 받으며 아기상어의 여행은 끝난다.
자기보다 가까운물고기를 먼저 먹고, 최단 거리 물고기가 많으면 위, 왼쪽 순서로 먹는다 -> bfs
처음에 단순히 델타 순서로 하면 조건을 만족하지 않을까했는데 자신보다 큰 물고기가 있는칸은 가지 못하므로, 델타 순서의 의미가 없어짐 결국 재정렬이 필요. 
최단거리에서 먹을 수 이쓴ㄴ 물고기들의 리스트를 구하는 bfs함수를 정의하고 while문을 돌면서 bfs의 재귀를 돌린다.
문제의 조건이 많아지니 bfs를 만드는것 자체가 어려웠다. while문을 따로 두번써야하는데.. 역시 재귀가 어려운가 싶다.
bfs 재귀돌리기
bfs/dfs 문제를 더 풀어봐야겠다.
* 당분간 아기상어 노래 금지 *
=> [250828]시뮬레이션 문제풀이/hemu

yj-yuee/조합/250901/팩토리얼.py
- **문제 제목**: 팩토리얼
- **문제 링크**: https://www.acmicpc.net/problem/10872
- **플랫폼**: 백준
- **난이도**: 브론즈 3 
팩토리얼 구하기 
재귀로 풀기
재귀가 어려웠던거 같기도....
재귀가 돌아가는 순서
재귀 단계별로 풀기
=> [250901] 기타 문제 풀이 / yj-yuee

hemu/BFS_DFS/250901/BOJ_7562_나이트의이동.py
[BOJ_7562]나이트의 이동/hemu
- **문제 제목**: 나이트의 이동
- **문제 링크**: https://www.acmicpc.net/problem/7562
- **플랫폼**: 백준
- **난이도**: 실버1
최소 거리 -> 최단거리 ->bfs
방향이 주어짐 -> 델타에서 쓸방향 계싼
나이트가 서있는 좌표 -> start 좌표
나이트가 도착할 좌표 -> while 종료조건
bfs로 최단거리 찾기
거리를 구하는게 항상 헷갈린다.
bfs 진행하면서 거리구하기
dfs 와 백트래킹 연습하기
=> [250901] 기타문제풀이/hemu
